version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.stage
    restart: always
    container_name: frontend-social-js
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
